#!/bin/sh

# Copyright (c) 2014-2016 Benjamin Althues <benjamin@babab.nl>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

VERSION="$(git tag | tail -1 || echo dev)"

_clean()
{
    rm -rf  vendor lib-examples/vendor project-skeleton/vendor
    rm -f   composer.lock lib-examples/composer.lock project-skeleton/composer.lock
}

_composer()
{
    composer update
    cd lib-examples
    composer update
    cd ../project-skeleton
    cp composer.json composer.json.bak
    cp composer-dev.json composer.json
    composer update
    mv composer.json.bak composer.json
}

_dist()
{
    mkdir -p dist/simphplist-${VERSION}
    cp -r src README.rst composer.json dist/simphplist-${VERSION}
    tar -czvf dist/simphplist-${VERSION}.tar.gz dist/simphplist-${VERSION}
}

_docs()
{
    cp docs/docs.md docs/slate/source/index.md
    cd docs/slate
    rake build
}

_serve()
{
    case "$1" in
        "examples") cd lib-examples/public;;
        "skeleton") cd project-skeleton/public;;
        *)
            echo ./setup serve' <examples | skeleton>'
            exit 1
            ;;
    esac
    php -S 127.0.0.1:8080
}

_usage()
{
    echo ./setup clean
    echo ./setup composer
    echo ./setup dist
    echo ./setup docs
    echo ./setup serve' <examples | skeleton>'
}

_main()
{
    case "$1" in
        "clean")    _clean;;
        "composer") _composer;;
        "dist")     _dist;;
        "docs")     _docs;;
        "serve")    _serve $2;;
        *)          _usage;;
    esac
}
_main $*
