#!/bin/sh

# Copyright (c) 2014-2015 Benjamin Althues <benjamin@babab.nl>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

VERSION="$(git tag | tail -1 || echo dev)"

_clean()
{
    rm -rf  dist
    rm -rf  docs/html docs/latex
    rm -rf  vendor          examples/vendor
    rm -f   composer.lock   examples/composer.lock
}

_composer()
{
    composer update
    cd examples
    composer update
}

_dist()
{
    mkdir -p dist/simphplist-${VERSION}
    cp -r src README.rst composer.json dist/simphplist-${VERSION}
    tar -czvf dist/simphplist-${VERSION}.tar.gz dist/simphplist-${VERSION}
}

_docs()
{
    cd docs
    doxygen Doxyfile
}

_usage()
{
    echo ./setup clean
    echo ./setup composer
    echo ./setup dist
    echo ./setup docs
}

_main()
{
    case "$1" in
        "clean")    _clean;;
        "composer") _composer;;
        "dist")     _dist;;
        "docs")     _docs;;
        *)          _usage;;
    esac
}
_main $1
